In [1]:
import pandas as pd

In [2]:
import numpy as np

In [ ]:
# Create a DataFrame containing student information like Name, Age, Department, %Marks

In [22]:
student_info={'Name' : ['Aditya', 'Avani', 'Aditi', 'Ajay', 'Amol'],
       'Age' : [23, 25, 30, 28, 29],
       'Department': ['ai', 'dac', 'ditiss', 'dbda', 'dac'],
        '%Marks':[90,78,89,76,88]}
df_d = pd.DataFrame(student_info)
df_d

     Name  Age Department  %Marks
0  Aditya   23         ai      90
1   Avani   25        dac      78
2   Aditi   30     ditiss      89
3    Ajay   28       dbda      76
4    Amol   29        dac      88

In [23]:
df_d.columns

Index(['Name', 'Age', 'Department', '%Marks'], dtype='str')

In [24]:
df_d['%Marks'].min()

np.int64(76)

In [25]:
df_d['%Marks'].max()

np.int64(90)

In [26]:
df_d['%Marks'].mean()

np.float64(84.2)

In [27]:
# Get unique values and student count for each Department

In [28]:
df_d['Department'].unique()

<StringArray>
['ai', 'dac', 'ditiss', 'dbda']
Length: 4, dtype: str

In [29]:
df_d['Department'].count()

np.int64(5)

In [ ]:
# Q2. Read csv file solar.csv
# a.	Display all the plants with capacity > 500 MW
# b.	Display plant details for New York plant
# c.	For all the plants display Average MW Per Plant and Generation (GWh)
# d.	Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)
# e.	List top 5 plants for their Generation
# f.	Display all plant details for states – California, Nevada, Arizona and Texas
# g.	Group the plants by region, find – min/max capacity plant for each group
# h.	Add following information to the existing details for the plants
# 	North Carolina	148	669	4.5	1162	North

In [109]:
df=pd.read_csv("solar.csv")
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [45]:
df[df["Installed Capacity (MW)"]>500]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
7,Florida,15,535,12.3,453,South

In [61]:
df.loc[df['State'] == 'New York']

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East

In [70]:
df[['Average MW Per Plant','Generation (GWh)']]

   Average MW Per Plant  Generation (GWh)
0                  15.3             10826
1                  22.5              2550
2                  21.6               557
3                   7.9               590
4                   5.9               235
5                  15.6               354
6                   4.1                84
7                  12.3               453

In [77]:
df.sort_values(by = ["Generation (GWh)","Installed Capacity (MW)"], ascending = [True,False])

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
7,Florida,15,535,12.3,453,South
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
1,Arizona,48,1078,22.5,2550,West
0,California,289,4395,15.3,10826,West

In [ ]:
# List top 5 plants for their Generation

In [88]:
df.sort_values(by = "Generation (GWh)" , ascending = False).head()

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
3,Chicago,33,261,7.9,590,North
2,Nevada,11,238,21.6,557,West
7,Florida,15,535,12.3,453,South

In [98]:
#Display all plant details for states – California, Nevada, Arizona and Texas
states = ["California", "Nevada", "Arizona","Texas"]
df[df["State"].isin (states)]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
5,Texas,12,187,15.6,354,South

In [104]:
#Group the plants by region, find – min/max capacity plant for each group
cgroups  =  df.groupby(df["Region"])
cgroups.min()

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh)
Region,,,,,
East,Connecticut,13,53,4.1,84
North,Chicago,33,261,7.9,590
South,Florida,12,187,12.3,354
West,Arizona,11,238,15.3,557

In [106]:
cgroups.max()

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh)
Region,,,,,
East,New York,20,118,5.9,235
North,Chicago,33,261,7.9,590
South,Texas,15,535,15.6,453
West,Nevada,289,4395,22.5,10826

In [79]:
#Add following information to the existing details for the plants
#North Carolina	148	669	4.5	1162	North

In [114]:
new_row = {
    "State": "North Carolina",
    "Number of Solar Plants": 148,
    "Installed Capacity (MW)": 669,
    "Average MW Per Plant": 4.5,
    "Generation (GWh)": 1162,
    "Region": "North"
}
df=pd.read_csv("solar.csv")

new=pd.DataFrame([new_row])
df = pd.concat([df, new], ignore_index=True)
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South
8,North Carolina,148,669,4.5,1162,North

In [ ]:
# Q.3Read csv gapminder2007.csv
# a.	Display data for all Asian countries
# b.	Display top and bottom 15 rows
# c.	Show all the rows where life expectancy is more than 50 years and less than 80 years
# d.	Show data for India, America and France
# e.	Show data for all countries where name starts with ‘A’
# f.	Show min/max and mean GDP and Population for each continent
# g.	Show population and life expectancy for all countries 
# h.	Sort the data by country names (ascending) and GDP (descending)
# i.	Find top 20 most populous countries
# j.	Delete all rows for a specific country
# k.	Change all column names to title case
# l.	Change column names: pop to Population, gdpPercap to GDP_Percap
# m.	Increase Life Expectancy by 2 years for all African countries
# n.	Find all the rows that contain NA values
# o.	Fill NA values with 0 for numeric columns

In [117]:
df=pd.read_csv("gapminder2007.csv")
df

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [120]:
# Display data for all Asian countries
df[df["continent"] == "Asia"]

                country         pop continent  lifeExp     gdpPercap
0           Afghanistan    31889923      Asia   43.828    974.580338
7               Bahrain      708573      Asia   75.635  29796.048340
8            Bangladesh   150448339      Asia   64.062   1391.253792
18             Cambodia    14131858      Asia   59.723   1713.778686
24                China  1318683096      Asia   72.961   4959.114854
55     Hong Kong, China     6980412      Asia   82.208  39724.978670
58                India  1110396331      Asia   64.698   2452.210407
59            Indonesia   223547000      Asia   70.650   3540.651564
60                 Iran    69453570      Asia   70.964  11605.714490
61                 Iraq    27499638      Asia   59.545   4471.061906
63               Israel     6426679      Asia   80.745  25523.277100
66                Japan   127467972      Asia   82.603  31656.068060
67               Jordan     6053193      Asia   72.535   4519.461171
69     Korea, Dem. Rep.    23301725      Asia   67.297   1593.065480
70          Korea, Rep.    49044790      Asia   78.623  23348.139730
71               Kuwait     2505559      Asia   77.588  47306.989780
72              Lebanon     3921278      Asia   71.993  10461.058680
78             Malaysia    24821286      Asia   74.241  12451.655800
83             Mongolia     2874127      Asia   66.803   3095.772271
87              Myanmar    47761980      Asia   62.069    944.000000
89                Nepal    28901790      Asia   63.785   1091.359778
96                 Oman     3204897      Asia   75.640  22316.192870
97             Pakistan   169270617      Asia   65.483   2605.947580
101         Philippines    91077287      Asia   71.688   3190.481016
109        Saudi Arabia    27601038      Asia   72.777  21654.831940
113           Singapore     4553009      Asia   79.972  47143.179640
119           Sri Lanka    20378239      Asia   72.396   3970.095407
124               Syria    19314747      Asia   74.143   4184.548089
125              Taiwan    23174294      Asia   78.400  28718.276840
127            Thailand    65068149      Asia   70.616   7458.396327
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906

In [121]:
# Display top and bottom 15 rows
df.head(15)

                   country        pop continent  lifeExp     gdpPercap
0              Afghanistan   31889923      Asia   43.828    974.580338
1                  Albania    3600523    Europe   76.423   5937.029526
2                  Algeria   33333216    Africa   72.301   6223.367465
3                   Angola   12420476    Africa   42.731   4797.231267
4                Argentina   40301927  Americas   75.320  12779.379640
5                Australia   20434176   Oceania   81.235  34435.367440
6                  Austria    8199783    Europe   79.829  36126.492700
7                  Bahrain     708573      Asia   75.635  29796.048340
8               Bangladesh  150448339      Asia   64.062   1391.253792
9                  Belgium   10392226    Europe   79.441  33692.605080
10                   Benin    8078314    Africa   56.728   1441.284873
11                 Bolivia    9119152  Americas   65.554   3822.137084
12  Bosnia and Herzegovina    4552198    Europe   74.852   7446.298803
13                Botswana    1639131    Africa   50.728  12569.851770
14                  Brazil  190010647  Americas   72.390   9065.800825

In [122]:
# Display top and bottom 15 rows
df.tail(15)

                 country        pop continent  lifeExp     gdpPercap
127             Thailand   65068149      Asia   70.616   7458.396327
128                 Togo    5701579    Africa   58.420    882.969944
129  Trinidad and Tobago    1056608  Americas   69.819  18008.509240
130              Tunisia   10276158    Africa   73.923   7092.923025
131               Turkey   71158647    Europe   71.777   8458.276384
132               Uganda   29170398    Africa   51.542   1056.380121
133       United Kingdom   60776238    Europe   79.425  33203.261280
134        United States  301139947  Americas   78.242  42951.653090
135              Uruguay    3447496  Americas   76.384  10611.462990
136            Venezuela   26084662  Americas   73.747  11415.805690
137              Vietnam   85262356      Asia   74.249   2441.576404
138   West Bank and Gaza    4018332      Asia   73.422   3025.349798
139          Yemen, Rep.   22211743      Asia   62.698   2280.769906
140               Zambia   11746035    Africa   42.384   1271.211593
141             Zimbabwe   12311143    Africa   43.487    469.709298

In [128]:
# Show all the rows where life expectancy is more than 50 years and less than 80 years
df[(df["lifeExp"]>50) & (df["lifeExp"]<80 )]

                country       pop continent  lifeExp     gdpPercap
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
4             Argentina  40301927  Americas   75.320  12779.379640
6               Austria   8199783    Europe   79.829  36126.492700
7               Bahrain    708573      Asia   75.635  29796.048340
..                  ...       ...       ...      ...           ...
135             Uruguay   3447496  Americas   76.384  10611.462990
136           Venezuela  26084662  Americas   73.747  11415.805690
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906

[110 rows x 5 columns]

In [ ]:
# Show data for India, America and France

In [131]:
df[df["country"].isin(["India","America","France"])]

   country         pop continent  lifeExp     gdpPercap
44  France    61083916    Europe   80.657  30470.016700
58   India  1110396331      Asia   64.698   2452.210407

In [132]:
# Show data for all countries where name starts with ‘A’

In [136]:
df[df["country"].str.startswith('A')]

       country       pop continent  lifeExp     gdpPercap
0  Afghanistan  31889923      Asia   43.828    974.580338
1      Albania   3600523    Europe   76.423   5937.029526
2      Algeria  33333216    Africa   72.301   6223.367465
3       Angola  12420476    Africa   42.731   4797.231267
4    Argentina  40301927  Americas   75.320  12779.379640
5    Australia  20434176   Oceania   81.235  34435.367440
6      Austria   8199783    Europe   79.829  36126.492700

In [143]:
# Show min/max and mean GDP and Population for each continent
df.groupby('continent').agg({
    'gdpPercap': ['min','max','mean'],
    'pop' : ['min','max','mean']
})

              gdpPercap                                 pop              \
                    min          max          mean      min         max
continent
Africa       277.551859  13206.48452   3089.032605   199579   135031164
Americas    1201.637154  42951.65309  11003.031625  1056608   301139947
Asia         944.000000  47306.98978  12473.026870   708573  1318683096
Europe      5937.029526  49357.19017  25054.481636   301931    82400996
Oceania    25185.009110  34435.36744  29810.188275  4115771    20434176


                   mean
continent
Africa     1.787576e+07
Americas   3.595485e+07
Asia       1.155138e+08
Europe     1.953662e+07
Oceania    1.227497e+07

In [148]:
# Show population and life expectancy for all countries 
df[['country','pop','lifeExp']]

                country       pop  lifeExp
0           Afghanistan  31889923   43.828
1               Albania   3600523   76.423
2               Algeria  33333216   72.301
3                Angola  12420476   42.731
4             Argentina  40301927   75.320
..                  ...       ...      ...
137             Vietnam  85262356   74.249
138  West Bank and Gaza   4018332   73.422
139         Yemen, Rep.  22211743   62.698
140              Zambia  11746035   42.384
141            Zimbabwe  12311143   43.487

[142 rows x 3 columns]

In [150]:
# Sort the data by country names (ascending) and GDP (descending)
df.sort_values(by = ['country','gdpPercap'],ascending=[True,False])

                country       pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923      Asia   43.828    974.580338
1               Albania   3600523    Europe   76.423   5937.029526
2               Algeria  33333216    Africa   72.301   6223.367465
3                Angola  12420476    Africa   42.731   4797.231267
4             Argentina  40301927  Americas   75.320  12779.379640
..                  ...       ...       ...      ...           ...
137             Vietnam  85262356      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743      Asia   62.698   2280.769906
140              Zambia  11746035    Africa   42.384   1271.211593
141            Zimbabwe  12311143    Africa   43.487    469.709298

[142 rows x 5 columns]

In [153]:
df.sort_values(by = ['pop'],ascending=False)

                   country         pop continent  lifeExp     gdpPercap
24                   China  1318683096      Asia   72.961   4959.114854
58                   India  1110396331      Asia   64.698   2452.210407
134          United States   301139947  Americas   78.242  42951.653090
59               Indonesia   223547000      Asia   70.650   3540.651564
14                  Brazil   190010647  Americas   72.390   9065.800825
..                     ...         ...       ...      ...           ...
84              Montenegro      684736    Europe   74.543   9253.896111
40       Equatorial Guinea      551201    Africa   51.579  12154.089750
35                Djibouti      496374    Africa   54.791   2082.481567
57                 Iceland      301931    Europe   81.757  36180.789190
108  Sao Tome and Principe      199579    Africa   65.528   1598.435089

[142 rows x 5 columns]

In [164]:
df.tail(20)

                 Country  Population Continent  Lifeexp    GDP_Percap
122               Sweden     9031088    Europe   80.884  33859.748350
123          Switzerland     7554661    Europe   81.701  37506.419070
124                Syria    19314747      Asia   74.143   4184.548089
125               Taiwan    23174294      Asia   78.400  28718.276840
126             Tanzania    38139640    Africa   54.517   1107.482182
127             Thailand    65068149      Asia   70.616   7458.396327
128                 Togo     5701579    Africa   60.420    882.969944
129  Trinidad and Tobago     1056608  Americas   69.819  18008.509240
130              Tunisia    10276158    Africa   75.923   7092.923025
131               Turkey    71158647    Europe   71.777   8458.276384
132               Uganda    29170398    Africa   53.542   1056.380121
133       United Kingdom    60776238    Europe   79.425  33203.261280
134        United States   301139947  Americas   78.242  42951.653090
135              Uruguay     3447496  Americas   76.384  10611.462990
136            Venezuela    26084662  Americas   73.747  11415.805690
137              Vietnam    85262356      Asia   74.249   2441.576404
138   West Bank and Gaza     4018332      Asia   73.422   3025.349798
139          Yemen, Rep.    22211743      Asia   62.698   2280.769906
140               Zambia    11746035    Africa   44.384   1271.211593
141             Zimbabwe    12311143    Africa   45.487    469.709298

In [166]:
# Delete all rows for a specific country
df = df[df['Country'] != 'Sweden']
df

                Country  Population Continent  Lifeexp    GDP_Percap
0           Afghanistan    31889923      Asia   43.828    974.580338
2               Algeria    33333216    Africa   74.301   6223.367465
3                Angola    12420476    Africa   44.731   4797.231267
4             Argentina    40301927  Americas   75.320  12779.379640
5             Australia    20434176   Oceania   81.235  34435.367440
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906
140              Zambia    11746035    Africa   44.384   1271.211593
141            Zimbabwe    12311143    Africa   45.487    469.709298

[140 rows x 5 columns]

In [172]:
# Change all column names to title case
df.columns = [col.title() for col in df.columns]
df.columns

Index(['Country', 'Population', 'Continent', 'Lifeexp', 'Gdp_Percap'], dtype='str')

In [175]:
# Change specific column names (Note: names reflect title case from previous case)
df = df.rename(columns={'Gdppercap': 'GDP_Percap'})
df

                Country  Population Continent  Lifeexp    Gdp_Percap
0           Afghanistan    31889923      Asia   43.828    974.580338
2               Algeria    33333216    Africa   74.301   6223.367465
3                Angola    12420476    Africa   44.731   4797.231267
4             Argentina    40301927  Americas   75.320  12779.379640
5             Australia    20434176   Oceania   81.235  34435.367440
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906
140              Zambia    11746035    Africa   44.384   1271.211593
141            Zimbabwe    12311143    Africa   45.487    469.709298

[140 rows x 5 columns]

In [179]:
# Increase Life Expectancy by 2 years for all African countries
# (Note: Using .loc to avoid SettingWithCopy warnings)
df.loc[df['Continent'] == 'Australia', 'Lifeexp'] += 2
df

                Country  Population Continent  Lifeexp    Gdp_Percap
0           Afghanistan    31889923      Asia   43.828    974.580338
2               Algeria    33333216    Africa   78.301   6223.367465
3                Angola    12420476    Africa   48.731   4797.231267
4             Argentina    40301927  Americas   75.320  12779.379640
5             Australia    20434176   Oceania   81.235  34435.367440
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906
140              Zambia    11746035    Africa   48.384   1271.211593
141            Zimbabwe    12311143    Africa   49.487    469.709298

[140 rows x 5 columns]

In [180]:
# Find all the rows that contain NA values
rows_with_nan = df[df.isnull().any(axis=1)]
rows_with_nan

Empty DataFrame
Columns: [Country, Population, Continent, Lifeexp, Gdp_Percap]
Index: []

In [182]:
# Fill NA values with 0 for numeric columns
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(0)
df

                Country  Population Continent  Lifeexp    Gdp_Percap
0           Afghanistan    31889923      Asia   43.828    974.580338
2               Algeria    33333216    Africa   78.301   6223.367465
3                Angola    12420476    Africa   48.731   4797.231267
4             Argentina    40301927  Americas   75.320  12779.379640
5             Australia    20434176   Oceania   81.235  34435.367440
..                  ...         ...       ...      ...           ...
137             Vietnam    85262356      Asia   74.249   2441.576404
138  West Bank and Gaza     4018332      Asia   73.422   3025.349798
139         Yemen, Rep.    22211743      Asia   62.698   2280.769906
140              Zambia    11746035    Africa   48.384   1271.211593
141            Zimbabwe    12311143    Africa   49.487    469.709298

[140 rows x 5 columns]