In [21]:
import pandas as pd
import numpy as np

In [22]:
people = {'first' : ['Shivansh', 'Rudra', 'Anish', np.nan, 'Avani', np.nan, 'NA'],
            'last' : ['P', 'N', 'Missing', 'NA', 'Missing', None, np.nan],
            'email' : ['shiv@gmail.com', 'rudra@gmail.com', 'anish@gmail.com', 'NA', 'avani@gmail.com', np.nan, np.nan],
             'age' : [42, 13, 43, None, 15, None, 40]}
df = pd.DataFrame(people)
df

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
3       NaN       NA               NA   NaN
4     Avani  Missing  avani@gmail.com  15.0
5       NaN     None              NaN   NaN
6        NA      NaN              NaN  40.0

In [5]:
df.dropna(how='any')

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
4     Avani  Missing  avani@gmail.com  15.0

In [24]:
df.dropna(how='all')

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
3       NaN       NA               NA   NaN
4     Avani  Missing  avani@gmail.com  15.0
6        NA      NaN              NaN  40.0

In [25]:
df.dropna(subset=['email'])

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
3       NaN       NA               NA   NaN
4     Avani  Missing  avani@gmail.com  15.0

In [26]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3   True  False  False   True
4  False  False  False  False
5   True   True   True   True
6  False   True   True  False

In [28]:
df.fillna({'email': 'NA','age':0})

      first     last            email   age
0  Shivansh        P   shiv@gmail.com  42.0
1     Rudra        N  rudra@gmail.com  13.0
2     Anish  Missing  anish@gmail.com  43.0
3       NaN       NA               NA   0.0
4     Avani  Missing  avani@gmail.com  15.0
5       NaN     None               NA   0.0
6        NA      NaN               NA  40.0