In [1]:
import pandas as pd
import numpy as np

In [2]:
names = ['Aditya', 'Avani', 'Aditi', 'Ajay', 'Amol']
series = pd.Series(names)
series

0    Aditya
1     Avani
2     Aditi
3      Ajay
4      Amol
dtype: object

In [3]:
arr = np.random.randint(10,100,10)
arr

array([31, 90, 50, 85, 93, 40, 28, 16, 42, 55], dtype=int32)

In [4]:
series_n = pd.Series(arr)
series_n

0    31
1    90
2    50
3    85
4    93
5    40
6    28
7    16
8    42
9    55
dtype: int32

In [5]:
head_office = {'USA':'NYC', 'India':'Pune', 'UAE':'Dubai', 'France':'Paris', 'UK': 'London'}
series_h = pd.Series(head_office)
series_h

USA          NYC
India       Pune
UAE        Dubai
France     Paris
UK        London
dtype: object

In [6]:
series_h.values

array(['NYC', 'Pune', 'Dubai', 'Paris', 'London'], dtype=object)

In [7]:
series_h.index

Index(['USA', 'India', 'UAE', 'France', 'UK'], dtype='object')

In [8]:
series_h.loc['India']

'Pune'

In [9]:
series_h.iloc[3]

'Paris'

In [10]:
series_n.loc[2]

np.int32(50)

In [11]:
series_h.loc['India':'France']

India      Pune
UAE       Dubai
France    Paris
dtype: object

In [12]:
series_h.iloc[0:3]

USA        NYC
India     Pune
UAE      Dubai
dtype: object

In [13]:
series_h.iloc[0:]

USA          NYC
India       Pune
UAE        Dubai
France     Paris
UK        London
dtype: object

In [14]:
series_h.iloc[:4]

USA         NYC
India      Pune
UAE       Dubai
France    Paris
dtype: object

In [ ]:
"""1. Combining multiple series object
2. dict - list of data,
3. DataFarme method (data=, index=, columns= )
4. by csv file
5. json file"""

In [16]:
count = {'USA':200, 'India':600, 'UAE':50, 'France':80, 'UK': 120}
series_c = pd.Series(count)
series_c

USA       200
India     600
UAE        50
France     80
UK        120
dtype: int64

In [18]:
df = pd.DataFrame({'Head Office':series_h, 'Employee Count': series_c})
df

       Head Office  Employee Count
USA            NYC             200
India         Pune             600
UAE          Dubai              50
France       Paris              80
UK          London             120

In [19]:
data = {'Name' : ['Aditya', 'Avani', 'Aditi', 'Ajay', 'Amol'],
       'Age' : [23, 25, 30, 28, 29],
       'City': ['Mumbai', 'Pune', 'Delhi', 'Pune', 'Mumbai']}
df_d = pd.DataFrame(data)
df_d

     Name  Age    City
0  Aditya   23  Mumbai
1   Avani   25    Pune
2   Aditi   30   Delhi
3    Ajay   28    Pune
4    Amol   29  Mumbai

In [21]:
c_data = pd.DataFrame(data = [[300,50,23], [150,30,33], [100,20,18]],
                      columns = ['Revenue', 'Market Share', 'Profit'],
                       index = ['Tata', 'Honda' ,'Kia'])
c_data

       Revenue  Market Share  Profit
Tata       300            50      23
Honda      150            30      33
Kia        100            20      18

In [22]:
df

       Head Office  Employee Count
USA            NYC             200
India         Pune             600
UAE          Dubai              50
France       Paris              80
UK          London             120

In [23]:
df.loc['India']

Head Office       Pune
Employee Count     600
Name: India, dtype: object

In [24]:
df.iloc[2]

Head Office       Dubai
Employee Count       50
Name: UAE, dtype: object

In [25]:
df.iloc[-2]

Head Office       Paris
Employee Count       80
Name: France, dtype: object

In [26]:
df.loc['India':'France']

       Head Office  Employee Count
India         Pune             600
UAE          Dubai              50
France       Paris              80

In [27]:
df.loc['India':'France', 'Head Office']

India      Pune
UAE       Dubai
France    Paris
Name: Head Office, dtype: object

In [28]:
c_data.loc['Tata':'Honda' , ['Revenue', 'Profit']]

       Revenue  Profit
Tata       300      23
Honda      150      33

In [29]:
c_data.loc['Tata':'Honda' , 'Revenue': 'Profit']

       Revenue  Market Share  Profit
Tata       300            50      23
Honda      150            30      33

In [30]:
c_data.iloc[1:2 , 0: 1]

       Revenue
Honda      150