In [20]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data.tsv', delimiter='\t', index_col='Office')
df

,Name,Position,Age,Start date,Salary
Office,,,,,
Tokyo,Airi Satou,Accountant,33,2008-11-28,"$162,700"
London,Angelica Ramos,Chief Executive Officer (CEO),47,2009-10-09,"$1,200,000"
San Francisco,Ashton Cox,Junior Technical Author,66,2009-01-12,"$86,000"
London,Bradley Greer,Software Engineer,41,2012-10-13,"$132,000"
San Francisco,Brenden Wagner,Software Engineer,28,2011-06-07,"$206,850"
New York,Brielle Williamson,Integration Specialist,61,2012-12-02,"$372,000"
London,Bruno Nash,Software Engineer,38,2011-05-03,"$163,500"
New York,Caesar Vance,Pre-Sales Support,21,2011-12-12,"$106,450"
New York,Cara Stevens,Sales Assistant,46,2011-12-06,"$145,600"
Edinburgh,Cedric Kelly,Senior Javascript Developer,22,2012-03-29,"$433,060"
San Francisco,Charde Marshall,Regional Director,36,2008-10-16,"$470,600"
San Francisco,Colleen Hurst,Javascript Developer,39,2009-09-15,"$205,500"
Edinburgh,Dai Rios,Personnel Lead,35,2012-09-26,"$217,500"
New York,Donna Snider,Customer Support,27,2011-01-25,"$112,000"
Sydney,Doris Wilder,Sales Assistant,23,2010-09-20,"$85,600"
San Francisco,Finn Camacho,Support Engineer,47,2009-07-07,"$87,500"
San Francisco,Fiona Green,Chief Operating Officer (COO),48,2010-03-11,"$850,000"
Tokyo,Garrett Winters,Accountant,63,2011-07-25,"$170,750"
San Francisco,Gavin Cortez,Team Leader,22,2008-10-26,"$235,500"
Edinburgh,Gavin Joyce,Developer,42,2010-12-22,"$92,575"
New York,Gloria Little,Systems Administrator,59,2009-04-10,"$237,500"
London,Haley Kennedy,Senior Marketing Designer,43,2012-12-18,"$313,500"
London,Hermione Butler,Regional Director,47,2011-03-21,"$356,250"
San Francisco,Herrod Chandler,Sales Assistant,59,2012-08-06,"$137,500"
San Francisco,Hope Fuentes,Secretary,41,2010-02-12,"$109,850"
San Francisco,Howard Hatfield,Office Manager,51,2008-12-16,"$164,500"
New York,Jackson Bradshaw,Director,65,2008-09-26,"$645,750"
London,Jena Gaines,Office Manager,30,2008-12-19,"$90,560"
New York,Jenette Caldwell,Development Lead,30,2011-09-03,"$345,000"
Edinburgh,Jennifer Acosta,Junior Javascript Developer,43,2013-02-01,"$75,650"
Singapore,Jennifer Chang,Regional Director,28,2010-11-14,"$357,650"
San Francisco,Jonas Alexander,Developer,30,2010-07-14,"$86,500"
London,Lael Greer,Systems Administrator,21,2009-02-27,"$103,500"
Edinburgh,Martena Mccray,Post-Sales support,46,2011-03-09,"$324,050"
Singapore,Michael Bruce,Javascript Developer,29,2011-06-27,"$183,000"
London,Michael Silva,Marketing Designer,66,2012-11-27,"$198,500"
Sydney,Michelle House,Integration Specialist,37,2011-06-02,"$95,400"
Singapore,Olivia Liang,Support Engineer,64,2011-02-03,"$234,500"
New York,Paul Byrd,Chief Financial Officer (CFO),64,2010-06-09,"$725,000"
London,Prescott Bartlett,Technical Author,27,2011-05-07,"$145,000"
Edinburgh,Quinn Flynn,Support Lead,22,2013-03-03,"$342,000"
Tokyo,Rhona Davidson,Integration Specialist,55,2010-10-14,"$327,900"
Tokyo,Sakura Yamamoto,Support Engineer,37,2009-08-19,"$139,575"
Singapore,Serge Baldwin,Data Coordinator,64,2012-04-09,"$138,575"
Edinburgh,Shad Decker,Regional Director,51,2008-11-13,"$183,000"
Tokyo,Shou Itou,Regional Marketing,20,2011-08-14,"$163,000"
Edinburgh,Sonya Frost,Software Engineer,23,2008-12-13,"$103,600"
London,Suki Burks,Developer,53,2009-10-22,"$114,500"
London,Tatyana Fitzpatrick,Regional Director,19,2010-03-17,"$385,750"
New York,Thor Walton,Developer,61,2013-08-11,"$98,540"
Edinburgh,Tiger Nixon,System Architect,61,2011-04-25,"$320,800"
London,Timothy Mooney,Office Manager,37,2008-12-11,"$136,200"
San Francisco,Unity Butler,Marketing Designer,47,2009-12-09,"$85,675"
San Francisco,Vivian Harrell,Financial Controller,62,2009-02-14,"$452,500"
New York,Yuri Berry,Chief Marketing Officer (CMO),40,2009-06-25,"$675,000"
New York,Zenaida Frank,Software Engineer,63,2010-01-04,"$125,250"
San Francisco,Zorita Serrano,Software Engineer,56,2012-06-01,"$115,000"
Office,Name,Position,Age,Start date,Salary

In [3]:
df.sort_values(by='Age')

,Name,Position,Age,Start date,Salary
Office,,,,,
London,Tatyana Fitzpatrick,Regional Director,19,2010-03-17,"$385,750"
Tokyo,Shou Itou,Regional Marketing,20,2011-08-14,"$163,000"
New York,Caesar Vance,Pre-Sales Support,21,2011-12-12,"$106,450"
London,Lael Greer,Systems Administrator,21,2009-02-27,"$103,500"
San Francisco,Gavin Cortez,Team Leader,22,2008-10-26,"$235,500"
Edinburgh,Quinn Flynn,Support Lead,22,2013-03-03,"$342,000"
Edinburgh,Cedric Kelly,Senior Javascript Developer,22,2012-03-29,"$433,060"
Edinburgh,Sonya Frost,Software Engineer,23,2008-12-13,"$103,600"
Sydney,Doris Wilder,Sales Assistant,23,2010-09-20,"$85,600"
London,Prescott Bartlett,Technical Author,27,2011-05-07,"$145,000"
New York,Donna Snider,Customer Support,27,2011-01-25,"$112,000"
San Francisco,Brenden Wagner,Software Engineer,28,2011-06-07,"$206,850"
Singapore,Jennifer Chang,Regional Director,28,2010-11-14,"$357,650"
Singapore,Michael Bruce,Javascript Developer,29,2011-06-27,"$183,000"
London,Jena Gaines,Office Manager,30,2008-12-19,"$90,560"
San Francisco,Jonas Alexander,Developer,30,2010-07-14,"$86,500"
New York,Jenette Caldwell,Development Lead,30,2011-09-03,"$345,000"
Tokyo,Airi Satou,Accountant,33,2008-11-28,"$162,700"
Edinburgh,Dai Rios,Personnel Lead,35,2012-09-26,"$217,500"
San Francisco,Charde Marshall,Regional Director,36,2008-10-16,"$470,600"
Sydney,Michelle House,Integration Specialist,37,2011-06-02,"$95,400"
London,Timothy Mooney,Office Manager,37,2008-12-11,"$136,200"
Tokyo,Sakura Yamamoto,Support Engineer,37,2009-08-19,"$139,575"
London,Bruno Nash,Software Engineer,38,2011-05-03,"$163,500"
San Francisco,Colleen Hurst,Javascript Developer,39,2009-09-15,"$205,500"
New York,Yuri Berry,Chief Marketing Officer (CMO),40,2009-06-25,"$675,000"
San Francisco,Hope Fuentes,Secretary,41,2010-02-12,"$109,850"
London,Bradley Greer,Software Engineer,41,2012-10-13,"$132,000"
Edinburgh,Gavin Joyce,Developer,42,2010-12-22,"$92,575"
London,Haley Kennedy,Senior Marketing Designer,43,2012-12-18,"$313,500"
Edinburgh,Jennifer Acosta,Junior Javascript Developer,43,2013-02-01,"$75,650"
Edinburgh,Martena Mccray,Post-Sales support,46,2011-03-09,"$324,050"
New York,Cara Stevens,Sales Assistant,46,2011-12-06,"$145,600"
London,Hermione Butler,Regional Director,47,2011-03-21,"$356,250"
London,Angelica Ramos,Chief Executive Officer (CEO),47,2009-10-09,"$1,200,000"
San Francisco,Unity Butler,Marketing Designer,47,2009-12-09,"$85,675"
San Francisco,Finn Camacho,Support Engineer,47,2009-07-07,"$87,500"
San Francisco,Fiona Green,Chief Operating Officer (COO),48,2010-03-11,"$850,000"
Edinburgh,Shad Decker,Regional Director,51,2008-11-13,"$183,000"
San Francisco,Howard Hatfield,Office Manager,51,2008-12-16,"$164,500"
London,Suki Burks,Developer,53,2009-10-22,"$114,500"
Tokyo,Rhona Davidson,Integration Specialist,55,2010-10-14,"$327,900"
San Francisco,Zorita Serrano,Software Engineer,56,2012-06-01,"$115,000"
San Francisco,Herrod Chandler,Sales Assistant,59,2012-08-06,"$137,500"
New York,Gloria Little,Systems Administrator,59,2009-04-10,"$237,500"
New York,Thor Walton,Developer,61,2013-08-11,"$98,540"
New York,Brielle Williamson,Integration Specialist,61,2012-12-02,"$372,000"
Edinburgh,Tiger Nixon,System Architect,61,2011-04-25,"$320,800"
San Francisco,Vivian Harrell,Financial Controller,62,2009-02-14,"$452,500"
New York,Zenaida Frank,Software Engineer,63,2010-01-04,"$125,250"
Tokyo,Garrett Winters,Accountant,63,2011-07-25,"$170,750"
Singapore,Olivia Liang,Support Engineer,64,2011-02-03,"$234,500"
Singapore,Serge Baldwin,Data Coordinator,64,2012-04-09,"$138,575"
New York,Paul Byrd,Chief Financial Officer (CFO),64,2010-06-09,"$725,000"
New York,Jackson Bradshaw,Director,65,2008-09-26,"$645,750"
London,Michael Silva,Marketing Designer,66,2012-11-27,"$198,500"
San Francisco,Ashton Cox,Junior Technical Author,66,2009-01-12,"$86,000"
Office,Name,Position,Age,Start date,Salary

In [4]:
df.sort_values(by='Age', ascending=False)

,Name,Position,Age,Start date,Salary
Office,,,,,
Office,Name,Position,Age,Start date,Salary
London,Michael Silva,Marketing Designer,66,2012-11-27,"$198,500"
San Francisco,Ashton Cox,Junior Technical Author,66,2009-01-12,"$86,000"
New York,Jackson Bradshaw,Director,65,2008-09-26,"$645,750"
Singapore,Serge Baldwin,Data Coordinator,64,2012-04-09,"$138,575"
Singapore,Olivia Liang,Support Engineer,64,2011-02-03,"$234,500"
New York,Paul Byrd,Chief Financial Officer (CFO),64,2010-06-09,"$725,000"
Tokyo,Garrett Winters,Accountant,63,2011-07-25,"$170,750"
New York,Zenaida Frank,Software Engineer,63,2010-01-04,"$125,250"
San Francisco,Vivian Harrell,Financial Controller,62,2009-02-14,"$452,500"
Edinburgh,Tiger Nixon,System Architect,61,2011-04-25,"$320,800"
New York,Brielle Williamson,Integration Specialist,61,2012-12-02,"$372,000"
New York,Thor Walton,Developer,61,2013-08-11,"$98,540"
San Francisco,Herrod Chandler,Sales Assistant,59,2012-08-06,"$137,500"
New York,Gloria Little,Systems Administrator,59,2009-04-10,"$237,500"
San Francisco,Zorita Serrano,Software Engineer,56,2012-06-01,"$115,000"
Tokyo,Rhona Davidson,Integration Specialist,55,2010-10-14,"$327,900"
London,Suki Burks,Developer,53,2009-10-22,"$114,500"
Edinburgh,Shad Decker,Regional Director,51,2008-11-13,"$183,000"
San Francisco,Howard Hatfield,Office Manager,51,2008-12-16,"$164,500"
San Francisco,Fiona Green,Chief Operating Officer (COO),48,2010-03-11,"$850,000"
London,Hermione Butler,Regional Director,47,2011-03-21,"$356,250"
San Francisco,Unity Butler,Marketing Designer,47,2009-12-09,"$85,675"
London,Angelica Ramos,Chief Executive Officer (CEO),47,2009-10-09,"$1,200,000"
San Francisco,Finn Camacho,Support Engineer,47,2009-07-07,"$87,500"
New York,Cara Stevens,Sales Assistant,46,2011-12-06,"$145,600"
Edinburgh,Martena Mccray,Post-Sales support,46,2011-03-09,"$324,050"
Edinburgh,Jennifer Acosta,Junior Javascript Developer,43,2013-02-01,"$75,650"
London,Haley Kennedy,Senior Marketing Designer,43,2012-12-18,"$313,500"
Edinburgh,Gavin Joyce,Developer,42,2010-12-22,"$92,575"
London,Bradley Greer,Software Engineer,41,2012-10-13,"$132,000"
San Francisco,Hope Fuentes,Secretary,41,2010-02-12,"$109,850"
New York,Yuri Berry,Chief Marketing Officer (CMO),40,2009-06-25,"$675,000"
San Francisco,Colleen Hurst,Javascript Developer,39,2009-09-15,"$205,500"
London,Bruno Nash,Software Engineer,38,2011-05-03,"$163,500"
Tokyo,Sakura Yamamoto,Support Engineer,37,2009-08-19,"$139,575"
London,Timothy Mooney,Office Manager,37,2008-12-11,"$136,200"
Sydney,Michelle House,Integration Specialist,37,2011-06-02,"$95,400"
San Francisco,Charde Marshall,Regional Director,36,2008-10-16,"$470,600"
Edinburgh,Dai Rios,Personnel Lead,35,2012-09-26,"$217,500"
Tokyo,Airi Satou,Accountant,33,2008-11-28,"$162,700"
London,Jena Gaines,Office Manager,30,2008-12-19,"$90,560"
New York,Jenette Caldwell,Development Lead,30,2011-09-03,"$345,000"
San Francisco,Jonas Alexander,Developer,30,2010-07-14,"$86,500"
Singapore,Michael Bruce,Javascript Developer,29,2011-06-27,"$183,000"
San Francisco,Brenden Wagner,Software Engineer,28,2011-06-07,"$206,850"
Singapore,Jennifer Chang,Regional Director,28,2010-11-14,"$357,650"
London,Prescott Bartlett,Technical Author,27,2011-05-07,"$145,000"
New York,Donna Snider,Customer Support,27,2011-01-25,"$112,000"
Sydney,Doris Wilder,Sales Assistant,23,2010-09-20,"$85,600"
Edinburgh,Sonya Frost,Software Engineer,23,2008-12-13,"$103,600"
Edinburgh,Quinn Flynn,Support Lead,22,2013-03-03,"$342,000"
San Francisco,Gavin Cortez,Team Leader,22,2008-10-26,"$235,500"
Edinburgh,Cedric Kelly,Senior Javascript Developer,22,2012-03-29,"$433,060"
New York,Caesar Vance,Pre-Sales Support,21,2011-12-12,"$106,450"
London,Lael Greer,Systems Administrator,21,2009-02-27,"$103,500"
Tokyo,Shou Itou,Regional Marketing,20,2011-08-14,"$163,000"
London,Tatyana Fitzpatrick,Regional Director,19,2010-03-17,"$385,750"

In [6]:
df.sort_values(by=['Age', 'Salary'], ascending=[True, False])

,Name,Position,Age,Start date,Salary
Office,,,,,
London,Tatyana Fitzpatrick,Regional Director,19,2010-03-17,"$385,750"
Tokyo,Shou Itou,Regional Marketing,20,2011-08-14,"$163,000"
New York,Caesar Vance,Pre-Sales Support,21,2011-12-12,"$106,450"
London,Lael Greer,Systems Administrator,21,2009-02-27,"$103,500"
Edinburgh,Cedric Kelly,Senior Javascript Developer,22,2012-03-29,"$433,060"
Edinburgh,Quinn Flynn,Support Lead,22,2013-03-03,"$342,000"
San Francisco,Gavin Cortez,Team Leader,22,2008-10-26,"$235,500"
Sydney,Doris Wilder,Sales Assistant,23,2010-09-20,"$85,600"
Edinburgh,Sonya Frost,Software Engineer,23,2008-12-13,"$103,600"
London,Prescott Bartlett,Technical Author,27,2011-05-07,"$145,000"
New York,Donna Snider,Customer Support,27,2011-01-25,"$112,000"
Singapore,Jennifer Chang,Regional Director,28,2010-11-14,"$357,650"
San Francisco,Brenden Wagner,Software Engineer,28,2011-06-07,"$206,850"
Singapore,Michael Bruce,Javascript Developer,29,2011-06-27,"$183,000"
London,Jena Gaines,Office Manager,30,2008-12-19,"$90,560"
San Francisco,Jonas Alexander,Developer,30,2010-07-14,"$86,500"
New York,Jenette Caldwell,Development Lead,30,2011-09-03,"$345,000"
Tokyo,Airi Satou,Accountant,33,2008-11-28,"$162,700"
Edinburgh,Dai Rios,Personnel Lead,35,2012-09-26,"$217,500"
San Francisco,Charde Marshall,Regional Director,36,2008-10-16,"$470,600"
Sydney,Michelle House,Integration Specialist,37,2011-06-02,"$95,400"
Tokyo,Sakura Yamamoto,Support Engineer,37,2009-08-19,"$139,575"
London,Timothy Mooney,Office Manager,37,2008-12-11,"$136,200"
London,Bruno Nash,Software Engineer,38,2011-05-03,"$163,500"
San Francisco,Colleen Hurst,Javascript Developer,39,2009-09-15,"$205,500"
New York,Yuri Berry,Chief Marketing Officer (CMO),40,2009-06-25,"$675,000"
London,Bradley Greer,Software Engineer,41,2012-10-13,"$132,000"
San Francisco,Hope Fuentes,Secretary,41,2010-02-12,"$109,850"
Edinburgh,Gavin Joyce,Developer,42,2010-12-22,"$92,575"
Edinburgh,Jennifer Acosta,Junior Javascript Developer,43,2013-02-01,"$75,650"
London,Haley Kennedy,Senior Marketing Designer,43,2012-12-18,"$313,500"
Edinburgh,Martena Mccray,Post-Sales support,46,2011-03-09,"$324,050"
New York,Cara Stevens,Sales Assistant,46,2011-12-06,"$145,600"
San Francisco,Finn Camacho,Support Engineer,47,2009-07-07,"$87,500"
San Francisco,Unity Butler,Marketing Designer,47,2009-12-09,"$85,675"
London,Hermione Butler,Regional Director,47,2011-03-21,"$356,250"
London,Angelica Ramos,Chief Executive Officer (CEO),47,2009-10-09,"$1,200,000"
San Francisco,Fiona Green,Chief Operating Officer (COO),48,2010-03-11,"$850,000"
Edinburgh,Shad Decker,Regional Director,51,2008-11-13,"$183,000"
San Francisco,Howard Hatfield,Office Manager,51,2008-12-16,"$164,500"
London,Suki Burks,Developer,53,2009-10-22,"$114,500"
Tokyo,Rhona Davidson,Integration Specialist,55,2010-10-14,"$327,900"
San Francisco,Zorita Serrano,Software Engineer,56,2012-06-01,"$115,000"
New York,Gloria Little,Systems Administrator,59,2009-04-10,"$237,500"
San Francisco,Herrod Chandler,Sales Assistant,59,2012-08-06,"$137,500"
New York,Thor Walton,Developer,61,2013-08-11,"$98,540"
New York,Brielle Williamson,Integration Specialist,61,2012-12-02,"$372,000"
Edinburgh,Tiger Nixon,System Architect,61,2011-04-25,"$320,800"
San Francisco,Vivian Harrell,Financial Controller,62,2009-02-14,"$452,500"
Tokyo,Garrett Winters,Accountant,63,2011-07-25,"$170,750"
New York,Zenaida Frank,Software Engineer,63,2010-01-04,"$125,250"
New York,Paul Byrd,Chief Financial Officer (CFO),64,2010-06-09,"$725,000"
Singapore,Olivia Liang,Support Engineer,64,2011-02-03,"$234,500"
Singapore,Serge Baldwin,Data Coordinator,64,2012-04-09,"$138,575"
New York,Jackson Bradshaw,Director,65,2008-09-26,"$645,750"
San Francisco,Ashton Cox,Junior Technical Author,66,2009-01-12,"$86,000"
London,Michael Silva,Marketing Designer,66,2012-11-27,"$198,500"
Office,Name,Position,Age,Start date,Salary

In [7]:
df.sort_index()

,Name,Position,Age,Start date,Salary
Office,,,,,
Edinburgh,Jennifer Acosta,Junior Javascript Developer,43,2013-02-01,"$75,650"
Edinburgh,Quinn Flynn,Support Lead,22,2013-03-03,"$342,000"
Edinburgh,Gavin Joyce,Developer,42,2010-12-22,"$92,575"
Edinburgh,Cedric Kelly,Senior Javascript Developer,22,2012-03-29,"$433,060"
Edinburgh,Shad Decker,Regional Director,51,2008-11-13,"$183,000"
Edinburgh,Tiger Nixon,System Architect,61,2011-04-25,"$320,800"
Edinburgh,Dai Rios,Personnel Lead,35,2012-09-26,"$217,500"
Edinburgh,Sonya Frost,Software Engineer,23,2008-12-13,"$103,600"
Edinburgh,Martena Mccray,Post-Sales support,46,2011-03-09,"$324,050"
London,Tatyana Fitzpatrick,Regional Director,19,2010-03-17,"$385,750"
London,Michael Silva,Marketing Designer,66,2012-11-27,"$198,500"
London,Jena Gaines,Office Manager,30,2008-12-19,"$90,560"
London,Prescott Bartlett,Technical Author,27,2011-05-07,"$145,000"
London,Hermione Butler,Regional Director,47,2011-03-21,"$356,250"
London,Haley Kennedy,Senior Marketing Designer,43,2012-12-18,"$313,500"
London,Suki Burks,Developer,53,2009-10-22,"$114,500"
London,Lael Greer,Systems Administrator,21,2009-02-27,"$103,500"
London,Timothy Mooney,Office Manager,37,2008-12-11,"$136,200"
London,Bruno Nash,Software Engineer,38,2011-05-03,"$163,500"
London,Bradley Greer,Software Engineer,41,2012-10-13,"$132,000"
London,Angelica Ramos,Chief Executive Officer (CEO),47,2009-10-09,"$1,200,000"
New York,Donna Snider,Customer Support,27,2011-01-25,"$112,000"
New York,Cara Stevens,Sales Assistant,46,2011-12-06,"$145,600"
New York,Gloria Little,Systems Administrator,59,2009-04-10,"$237,500"
New York,Caesar Vance,Pre-Sales Support,21,2011-12-12,"$106,450"
New York,Brielle Williamson,Integration Specialist,61,2012-12-02,"$372,000"
New York,Yuri Berry,Chief Marketing Officer (CMO),40,2009-06-25,"$675,000"
New York,Paul Byrd,Chief Financial Officer (CFO),64,2010-06-09,"$725,000"
New York,Jackson Bradshaw,Director,65,2008-09-26,"$645,750"
New York,Zenaida Frank,Software Engineer,63,2010-01-04,"$125,250"
New York,Thor Walton,Developer,61,2013-08-11,"$98,540"
New York,Jenette Caldwell,Development Lead,30,2011-09-03,"$345,000"
Office,Name,Position,Age,Start date,Salary
San Francisco,Brenden Wagner,Software Engineer,28,2011-06-07,"$206,850"
San Francisco,Colleen Hurst,Javascript Developer,39,2009-09-15,"$205,500"
San Francisco,Finn Camacho,Support Engineer,47,2009-07-07,"$87,500"
San Francisco,Fiona Green,Chief Operating Officer (COO),48,2010-03-11,"$850,000"
San Francisco,Vivian Harrell,Financial Controller,62,2009-02-14,"$452,500"
San Francisco,Jonas Alexander,Developer,30,2010-07-14,"$86,500"
San Francisco,Gavin Cortez,Team Leader,22,2008-10-26,"$235,500"
San Francisco,Charde Marshall,Regional Director,36,2008-10-16,"$470,600"
San Francisco,Unity Butler,Marketing Designer,47,2009-12-09,"$85,675"
San Francisco,Herrod Chandler,Sales Assistant,59,2012-08-06,"$137,500"
San Francisco,Hope Fuentes,Secretary,41,2010-02-12,"$109,850"
San Francisco,Howard Hatfield,Office Manager,51,2008-12-16,"$164,500"
San Francisco,Zorita Serrano,Software Engineer,56,2012-06-01,"$115,000"
San Francisco,Ashton Cox,Junior Technical Author,66,2009-01-12,"$86,000"
Singapore,Serge Baldwin,Data Coordinator,64,2012-04-09,"$138,575"
Singapore,Olivia Liang,Support Engineer,64,2011-02-03,"$234,500"
Singapore,Michael Bruce,Javascript Developer,29,2011-06-27,"$183,000"
Singapore,Jennifer Chang,Regional Director,28,2010-11-14,"$357,650"
Sydney,Michelle House,Integration Specialist,37,2011-06-02,"$95,400"
Sydney,Doris Wilder,Sales Assistant,23,2010-09-20,"$85,600"
Tokyo,Shou Itou,Regional Marketing,20,2011-08-14,"$163,000"
Tokyo,Sakura Yamamoto,Support Engineer,37,2009-08-19,"$139,575"
Tokyo,Rhona Davidson,Integration Specialist,55,2010-10-14,"$327,900"
Tokyo,Garrett Winters,Accountant,63,2011-07-25,"$170,750"
Tokyo,Airi Satou,Accountant,33,2008-11-28,"$162,700"

In [9]:
df['Age'].dtype

dtype('O')

In [11]:
df['Age'] = pd.to_numeric(df['Age'], errors ='coerce')

In [15]:
df['Age'].dtype

dtype('float64')

In [23]:
df.nsmallest(10, 'Age')

,Name,Position,Age,Start date,Salary
Office,,,,,
London,Tatyana Fitzpatrick,Regional Director,19.0,2010-03-17,NaN
Tokyo,Shou Itou,Regional Marketing,20.0,2011-08-14,NaN
New York,Caesar Vance,Pre-Sales Support,21.0,2011-12-12,NaN
London,Lael Greer,Systems Administrator,21.0,2009-02-27,NaN
Edinburgh,Cedric Kelly,Senior Javascript Developer,22.0,2012-03-29,NaN
San Francisco,Gavin Cortez,Team Leader,22.0,2008-10-26,NaN
Edinburgh,Quinn Flynn,Support Lead,22.0,2013-03-03,NaN
Sydney,Doris Wilder,Sales Assistant,23.0,2010-09-20,NaN
Edinburgh,Sonya Frost,Software Engineer,23.0,2008-12-13,NaN
New York,Donna Snider,Customer Support,27.0,2011-01-25,NaN

In [24]:
df.nlargest(10, 'Age')

,Name,Position,Age,Start date,Salary
Office,,,,,
San Francisco,Ashton Cox,Junior Technical Author,66.0,2009-01-12,NaN
London,Michael Silva,Marketing Designer,66.0,2012-11-27,NaN
New York,Jackson Bradshaw,Director,65.0,2008-09-26,NaN
Singapore,Olivia Liang,Support Engineer,64.0,2011-02-03,NaN
New York,Paul Byrd,Chief Financial Officer (CFO),64.0,2010-06-09,NaN
Singapore,Serge Baldwin,Data Coordinator,64.0,2012-04-09,NaN
Tokyo,Garrett Winters,Accountant,63.0,2011-07-25,NaN
New York,Zenaida Frank,Software Engineer,63.0,2010-01-04,NaN
San Francisco,Vivian Harrell,Financial Controller,62.0,2009-02-14,NaN
New York,Brielle Williamson,Integration Specialist,61.0,2012-12-02,NaN